<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                alt CDATA ""
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.4" release="Thu May 18 17:37:13 2017 -0700">
<training_set datafile="temp.fasta" length="197">
<alphabet name="Protein" like="protein">
<letter id="A" symbol="A" name="Alanine" colour="0000CC"/>
<letter id="C" symbol="C" name="Cysteine" colour="0000CC"/>
<letter id="D" symbol="D" name="Aspartic acid" colour="FF00FF"/>
<letter id="E" symbol="E" name="Glutamic acid" colour="FF00FF"/>
<letter id="F" symbol="F" name="Phenylalanine" colour="0000CC"/>
<letter id="G" symbol="G" name="Glycine" colour="FFB300"/>
<letter id="H" symbol="H" name="Histidine" colour="FFCCCC"/>
<letter id="I" symbol="I" name="Isoleucine" colour="0000CC"/>
<letter id="K" symbol="K" name="Lysine" colour="CC0000"/>
<letter id="L" symbol="L" name="Leucine" colour="0000CC"/>
<letter id="M" symbol="M" name="Methionine" colour="0000CC"/>
<letter id="N" symbol="N" name="Asparagine" colour="008000"/>
<letter id="P" symbol="P" name="Proline" colour="FFFF00"/>
<letter id="Q" symbol="Q" name="Glutamine" colour="008000"/>
<letter id="R" symbol="R" name="Arginine" colour="CC0000"/>
<letter id="S" symbol="S" name="Serine" colour="008000"/>
<letter id="T" symbol="T" name="Threonine" colour="008000"/>
<letter id="V" symbol="V" name="Valine" colour="0000CC"/>
<letter id="W" symbol="W" name="Tryptophan" colour="0000CC"/>
<letter id="Y" symbol="Y" name="Tyrosine" colour="33E6CC"/>
<letter id="X" symbol="X" aliases="*." equals="ACDEFGHIKLMNPQRSTVWY" name="Any amino acid"/>
<letter id="B" symbol="B" equals="DN" name="Asparagine or Aspartic acid"/>
<letter id="Z" symbol="Z" equals="EQ" name="Glutamine or Glutamic acid"/>
<letter id="J" symbol="J" equals="IL" name="Leucine or Isoleucine"/>
</alphabet>
<sequence id="sequence_0" name="seq_1" length="16" weight="1.000000" />
<sequence id="sequence_1" name="seq_2" length="16" weight="1.000000" />
<sequence id="sequence_2" name="seq_3" length="10" weight="1.000000" />
<sequence id="sequence_3" name="seq_4" length="16" weight="1.000000" />
<sequence id="sequence_4" name="seq_5" length="16" weight="1.000000" />
<sequence id="sequence_5" name="seq_6" length="10" weight="1.000000" />
<sequence id="sequence_6" name="seq_7" length="16" weight="1.000000" />
<sequence id="sequence_7" name="seq_8" length="16" weight="1.000000" />
<sequence id="sequence_8" name="seq_9" length="16" weight="1.000000" />
<sequence id="sequence_9" name="seq_10" length="16" weight="1.000000" />
<sequence id="sequence_10" name="seq_11" length="16" weight="1.000000" />
<sequence id="sequence_11" name="seq_12" length="16" weight="1.000000" />
<sequence id="sequence_12" name="seq_13" length="16" weight="1.000000" />
<sequence id="sequence_13" name="seq_14" length="16" weight="1.000000" />
<sequence id="sequence_14" name="seq_15" length="16" weight="1.000000" />
<sequence id="sequence_15" name="seq_16" length="10" weight="1.000000" />
<sequence id="sequence_16" name="seq_17" length="16" weight="1.000000" />
<sequence id="sequence_17" name="seq_18" length="16" weight="1.000000" />
<sequence id="sequence_18" name="seq_19" length="16" weight="1.000000" />
<sequence id="sequence_19" name="seq_20" length="16" weight="1.000000" />
<sequence id="sequence_20" name="seq_21" length="16" weight="1.000000" />
<sequence id="sequence_21" name="seq_22" length="16" weight="1.000000" />
<sequence id="sequence_22" name="seq_23" length="16" weight="1.000000" />
<sequence id="sequence_23" name="seq_24" length="16" weight="1.000000" />
<sequence id="sequence_24" name="seq_25" length="16" weight="1.000000" />
<sequence id="sequence_25" name="seq_26" length="16" weight="1.000000" />
<sequence id="sequence_26" name="seq_27" length="16" weight="1.000000" />
<sequence id="sequence_27" name="seq_28" length="16" weight="1.000000" />
<sequence id="sequence_28" name="seq_29" length="16" weight="1.000000" />
<sequence id="sequence_29" name="seq_30" length="10" weight="1.000000" />
<sequence id="sequence_30" name="seq_31" length="16" weight="1.000000" />
<sequence id="sequence_31" name="seq_32" length="16" weight="1.000000" />
<sequence id="sequence_32" name="seq_33" length="16" weight="1.000000" />
<sequence id="sequence_33" name="seq_34" length="16" weight="1.000000" />
<sequence id="sequence_34" name="seq_35" length="16" weight="1.000000" />
<sequence id="sequence_35" name="seq_36" length="16" weight="1.000000" />
<sequence id="sequence_36" name="seq_37" length="10" weight="1.000000" />
<sequence id="sequence_37" name="seq_38" length="16" weight="1.000000" />
<sequence id="sequence_38" name="seq_39" length="16" weight="1.000000" />
<sequence id="sequence_39" name="seq_40" length="16" weight="1.000000" />
<sequence id="sequence_40" name="seq_41" length="16" weight="1.000000" />
<sequence id="sequence_41" name="seq_42" length="16" weight="1.000000" />
<sequence id="sequence_42" name="seq_43" length="16" weight="1.000000" />
<sequence id="sequence_43" name="seq_44" length="16" weight="1.000000" />
<sequence id="sequence_44" name="seq_45" length="16" weight="1.000000" />
<sequence id="sequence_45" name="seq_46" length="16" weight="1.000000" />
<sequence id="sequence_46" name="seq_47" length="16" weight="1.000000" />
<sequence id="sequence_47" name="seq_48" length="16" weight="1.000000" />
<sequence id="sequence_48" name="seq_49" length="16" weight="1.000000" />
<sequence id="sequence_49" name="seq_50" length="16" weight="1.000000" />
<sequence id="sequence_50" name="seq_51" length="16" weight="1.000000" />
<sequence id="sequence_51" name="seq_52" length="16" weight="1.000000" />
<sequence id="sequence_52" name="seq_53" length="16" weight="1.000000" />
<sequence id="sequence_53" name="seq_54" length="16" weight="1.000000" />
<sequence id="sequence_54" name="seq_55" length="16" weight="1.000000" />
<sequence id="sequence_55" name="seq_56" length="10" weight="1.000000" />
<sequence id="sequence_56" name="seq_57" length="16" weight="1.000000" />
<sequence id="sequence_57" name="seq_58" length="16" weight="1.000000" />
<sequence id="sequence_58" name="seq_59" length="16" weight="1.000000" />
<sequence id="sequence_59" name="seq_60" length="16" weight="1.000000" />
<sequence id="sequence_60" name="seq_61" length="16" weight="1.000000" />
<sequence id="sequence_61" name="seq_62" length="16" weight="1.000000" />
<sequence id="sequence_62" name="seq_63" length="16" weight="1.000000" />
<sequence id="sequence_63" name="seq_64" length="16" weight="1.000000" />
<sequence id="sequence_64" name="seq_65" length="16" weight="1.000000" />
<sequence id="sequence_65" name="seq_66" length="16" weight="1.000000" />
<sequence id="sequence_66" name="seq_67" length="16" weight="1.000000" />
<sequence id="sequence_67" name="seq_68" length="16" weight="1.000000" />
<sequence id="sequence_68" name="seq_69" length="16" weight="1.000000" />
<sequence id="sequence_69" name="seq_70" length="16" weight="1.000000" />
<sequence id="sequence_70" name="seq_71" length="16" weight="1.000000" />
<sequence id="sequence_71" name="seq_72" length="16" weight="1.000000" />
<sequence id="sequence_72" name="seq_73" length="9" weight="1.000000" />
<sequence id="sequence_73" name="seq_74" length="16" weight="1.000000" />
<sequence id="sequence_74" name="seq_75" length="9" weight="1.000000" />
<sequence id="sequence_75" name="seq_76" length="16" weight="1.000000" />
<sequence id="sequence_76" name="seq_77" length="16" weight="1.000000" />
<sequence id="sequence_77" name="seq_78" length="16" weight="1.000000" />
<sequence id="sequence_78" name="seq_79" length="16" weight="1.000000" />
<sequence id="sequence_79" name="seq_80" length="16" weight="1.000000" />
<sequence id="sequence_80" name="seq_81" length="16" weight="1.000000" />
<sequence id="sequence_81" name="seq_82" length="16" weight="1.000000" />
<sequence id="sequence_82" name="seq_83" length="16" weight="1.000000" />
<sequence id="sequence_83" name="seq_84" length="16" weight="1.000000" />
<sequence id="sequence_84" name="seq_85" length="16" weight="1.000000" />
<sequence id="sequence_85" name="seq_86" length="16" weight="1.000000" />
<sequence id="sequence_86" name="seq_87" length="16" weight="1.000000" />
<sequence id="sequence_87" name="seq_88" length="16" weight="1.000000" />
<sequence id="sequence_88" name="seq_89" length="16" weight="1.000000" />
<sequence id="sequence_89" name="seq_90" length="16" weight="1.000000" />
<sequence id="sequence_90" name="seq_91" length="9" weight="1.000000" />
<sequence id="sequence_91" name="seq_92" length="16" weight="1.000000" />
<sequence id="sequence_92" name="seq_93" length="16" weight="1.000000" />
<sequence id="sequence_93" name="seq_94" length="16" weight="1.000000" />
<sequence id="sequence_94" name="seq_95" length="16" weight="1.000000" />
<sequence id="sequence_95" name="seq_96" length="16" weight="1.000000" />
<sequence id="sequence_96" name="seq_97" length="16" weight="1.000000" />
<sequence id="sequence_97" name="seq_98" length="16" weight="1.000000" />
<sequence id="sequence_98" name="seq_99" length="16" weight="1.000000" />
<sequence id="sequence_99" name="seq_100" length="16" weight="1.000000" />
<sequence id="sequence_100" name="seq_101" length="16" weight="1.000000" />
<sequence id="sequence_101" name="seq_102" length="9" weight="1.000000" />
<sequence id="sequence_102" name="seq_103" length="16" weight="1.000000" />
<sequence id="sequence_103" name="seq_104" length="16" weight="1.000000" />
<sequence id="sequence_104" name="seq_105" length="9" weight="1.000000" />
<sequence id="sequence_105" name="seq_106" length="16" weight="1.000000" />
<sequence id="sequence_106" name="seq_107" length="16" weight="1.000000" />
<sequence id="sequence_107" name="seq_108" length="16" weight="1.000000" />
<sequence id="sequence_108" name="seq_109" length="16" weight="1.000000" />
<sequence id="sequence_109" name="seq_110" length="16" weight="1.000000" />
<sequence id="sequence_110" name="seq_111" length="9" weight="1.000000" />
<sequence id="sequence_111" name="seq_112" length="16" weight="1.000000" />
<sequence id="sequence_112" name="seq_113" length="16" weight="1.000000" />
<sequence id="sequence_113" name="seq_114" length="16" weight="1.000000" />
<sequence id="sequence_114" name="seq_115" length="16" weight="1.000000" />
<sequence id="sequence_115" name="seq_116" length="16" weight="1.000000" />
<sequence id="sequence_116" name="seq_117" length="16" weight="1.000000" />
<sequence id="sequence_117" name="seq_118" length="16" weight="1.000000" />
<sequence id="sequence_118" name="seq_119" length="16" weight="1.000000" />
<sequence id="sequence_119" name="seq_120" length="16" weight="1.000000" />
<sequence id="sequence_120" name="seq_121" length="16" weight="1.000000" />
<sequence id="sequence_121" name="seq_122" length="16" weight="1.000000" />
<sequence id="sequence_122" name="seq_123" length="16" weight="1.000000" />
<sequence id="sequence_123" name="seq_124" length="16" weight="1.000000" />
<sequence id="sequence_124" name="seq_125" length="16" weight="1.000000" />
<sequence id="sequence_125" name="seq_126" length="16" weight="1.000000" />
<sequence id="sequence_126" name="seq_127" length="9" weight="1.000000" />
<sequence id="sequence_127" name="seq_128" length="16" weight="1.000000" />
<sequence id="sequence_128" name="seq_129" length="16" weight="1.000000" />
<sequence id="sequence_129" name="seq_130" length="9" weight="1.000000" />
<sequence id="sequence_130" name="seq_131" length="16" weight="1.000000" />
<sequence id="sequence_131" name="seq_132" length="16" weight="1.000000" />
<sequence id="sequence_132" name="seq_133" length="16" weight="1.000000" />
<sequence id="sequence_133" name="seq_134" length="16" weight="1.000000" />
<sequence id="sequence_134" name="seq_135" length="16" weight="1.000000" />
<sequence id="sequence_135" name="seq_136" length="9" weight="1.000000" />
<sequence id="sequence_136" name="seq_137" length="9" weight="1.000000" />
<sequence id="sequence_137" name="seq_138" length="16" weight="1.000000" />
<sequence id="sequence_138" name="seq_139" length="16" weight="1.000000" />
<sequence id="sequence_139" name="seq_140" length="16" weight="1.000000" />
<sequence id="sequence_140" name="seq_141" length="16" weight="1.000000" />
<sequence id="sequence_141" name="seq_142" length="16" weight="1.000000" />
<sequence id="sequence_142" name="seq_143" length="16" weight="1.000000" />
<sequence id="sequence_143" name="seq_144" length="16" weight="1.000000" />
<sequence id="sequence_144" name="seq_145" length="16" weight="1.000000" />
<sequence id="sequence_145" name="seq_146" length="16" weight="1.000000" />
<sequence id="sequence_146" name="seq_147" length="16" weight="1.000000" />
<sequence id="sequence_147" name="seq_148" length="16" weight="1.000000" />
<sequence id="sequence_148" name="seq_149" length="16" weight="1.000000" />
<sequence id="sequence_149" name="seq_150" length="16" weight="1.000000" />
<sequence id="sequence_150" name="seq_151" length="16" weight="1.000000" />
<sequence id="sequence_151" name="seq_152" length="16" weight="1.000000" />
<sequence id="sequence_152" name="seq_153" length="16" weight="1.000000" />
<sequence id="sequence_153" name="seq_154" length="16" weight="1.000000" />
<sequence id="sequence_154" name="seq_155" length="16" weight="1.000000" />
<sequence id="sequence_155" name="seq_156" length="16" weight="1.000000" />
<sequence id="sequence_156" name="seq_157" length="9" weight="1.000000" />
<sequence id="sequence_157" name="seq_158" length="9" weight="1.000000" />
<sequence id="sequence_158" name="seq_159" length="16" weight="1.000000" />
<sequence id="sequence_159" name="seq_160" length="16" weight="1.000000" />
<sequence id="sequence_160" name="seq_161" length="16" weight="1.000000" />
<sequence id="sequence_161" name="seq_162" length="16" weight="1.000000" />
<sequence id="sequence_162" name="seq_163" length="16" weight="1.000000" />
<sequence id="sequence_163" name="seq_164" length="16" weight="1.000000" />
<sequence id="sequence_164" name="seq_165" length="16" weight="1.000000" />
<sequence id="sequence_165" name="seq_166" length="16" weight="1.000000" />
<sequence id="sequence_166" name="seq_167" length="16" weight="1.000000" />
<sequence id="sequence_167" name="seq_168" length="16" weight="1.000000" />
<sequence id="sequence_168" name="seq_169" length="9" weight="1.000000" />
<sequence id="sequence_169" name="seq_170" length="16" weight="1.000000" />
<sequence id="sequence_170" name="seq_171" length="16" weight="1.000000" />
<sequence id="sequence_171" name="seq_172" length="16" weight="1.000000" />
<sequence id="sequence_172" name="seq_173" length="16" weight="1.000000" />
<sequence id="sequence_173" name="seq_174" length="16" weight="1.000000" />
<sequence id="sequence_174" name="seq_175" length="16" weight="1.000000" />
<sequence id="sequence_175" name="seq_176" length="9" weight="1.000000" />
<sequence id="sequence_176" name="seq_177" length="16" weight="1.000000" />
<sequence id="sequence_177" name="seq_178" length="16" weight="1.000000" />
<sequence id="sequence_178" name="seq_179" length="9" weight="1.000000" />
<sequence id="sequence_179" name="seq_180" length="16" weight="1.000000" />
<sequence id="sequence_180" name="seq_181" length="16" weight="1.000000" />
<sequence id="sequence_181" name="seq_182" length="16" weight="1.000000" />
<sequence id="sequence_182" name="seq_183" length="16" weight="1.000000" />
<sequence id="sequence_183" name="seq_184" length="16" weight="1.000000" />
<sequence id="sequence_184" name="seq_185" length="16" weight="1.000000" />
<sequence id="sequence_185" name="seq_186" length="9" weight="1.000000" />
<sequence id="sequence_186" name="seq_187" length="16" weight="1.000000" />
<sequence id="sequence_187" name="seq_188" length="16" weight="1.000000" />
<sequence id="sequence_188" name="seq_189" length="16" weight="1.000000" />
<sequence id="sequence_189" name="seq_190" length="16" weight="1.000000" />
<sequence id="sequence_190" name="seq_191" length="16" weight="1.000000" />
<sequence id="sequence_191" name="seq_192" length="16" weight="1.000000" />
<sequence id="sequence_192" name="seq_193" length="9" weight="1.000000" />
<sequence id="sequence_193" name="seq_194" length="9" weight="1.000000" />
<sequence id="sequence_194" name="seq_195" length="16" weight="1.000000" />
<sequence id="sequence_195" name="seq_196" length="16" weight="1.000000" />
<sequence id="sequence_196" name="seq_197" length="9" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.041</value>
<value letter_id="C">0.003</value>
<value letter_id="D">0.045</value>
<value letter_id="E">0.160</value>
<value letter_id="F">0.019</value>
<value letter_id="G">0.027</value>
<value letter_id="H">0.021</value>
<value letter_id="I">0.066</value>
<value letter_id="K">0.042</value>
<value letter_id="L">0.122</value>
<value letter_id="M">0.016</value>
<value letter_id="N">0.025</value>
<value letter_id="P">0.104</value>
<value letter_id="Q">0.051</value>
<value letter_id="R">0.032</value>
<value letter_id="S">0.095</value>
<value letter_id="T">0.057</value>
<value letter_id="V">0.053</value>
<value letter_id="W">0.003</value>
<value letter_id="Y">0.020</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme -oc bgamma.combined -nmotifs 1 -protein -mod oops -minw 9 -bfile bgfile.txt temp.fasta </command_line>
<host>nebula-2.biostat.wisc.edu</host>
<type>oops</type>
<nmotifs>1</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>9</min_width>
<max_width>9</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>197</minsites>
<maxsites>197</maxsites>
<wnsites>0.8</wnsites>
<spmap>pam</spmap>
<spfuzz>120</spfuzz>
<prior>dmix</prior>
<beta>0</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>197</num_sequences>
<num_positions>2983</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>none</strands>
<priors_file>prior30.plib</priors_file>
<reason_for_stopping>Stopped because requested number of motifs (1) found.</reason_for_stopping>
<background_frequencies source="bgfile.txt">
<alphabet_array>
<value letter_id="A">0.070</value>
<value letter_id="C">0.023</value>
<value letter_id="D">0.047</value>
<value letter_id="E">0.071</value>
<value letter_id="F">0.037</value>
<value letter_id="G">0.066</value>
<value letter_id="H">0.026</value>
<value letter_id="I">0.043</value>
<value letter_id="K">0.057</value>
<value letter_id="L">0.100</value>
<value letter_id="M">0.021</value>
<value letter_id="N">0.036</value>
<value letter_id="P">0.063</value>
<value letter_id="Q">0.048</value>
<value letter_id="R">0.056</value>
<value letter_id="S">0.083</value>
<value letter_id="T">0.054</value>
<value letter_id="V">0.060</value>
<value letter_id="W">0.012</value>
<value letter_id="Y">0.027</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="LPTIPEEE" alt="MEME-1" width="8" sites="197" ic="16.0" re="13.2" llr="1799" e_value="2.1e-478" bayes_threshold="2.61874" elapsed_time="17.456685">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-777</value>
<value letter_id="C">-763</value>
<value letter_id="D">-980</value>
<value letter_id="E">-939</value>
<value letter_id="F">-261</value>
<value letter_id="G">-959</value>
<value letter_id="H">-840</value>
<value letter_id="I">-137</value>
<value letter_id="K">-895</value>
<value letter_id="L">316</value>
<value letter_id="M">173</value>
<value letter_id="N">-890</value>
<value letter_id="P">-915</value>
<value letter_id="Q">-810</value>
<value letter_id="R">-857</value>
<value letter_id="S">-924</value>
<value letter_id="T">-761</value>
<value letter_id="V">-242</value>
<value letter_id="W">-689</value>
<value letter_id="Y">-696</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">3</value>
<value letter_id="C">-120</value>
<value letter_id="D">47</value>
<value letter_id="E">52</value>
<value letter_id="F">-126</value>
<value letter_id="G">-165</value>
<value letter_id="H">-125</value>
<value letter_id="I">-290</value>
<value letter_id="K">-57</value>
<value letter_id="L">-98</value>
<value letter_id="M">-191</value>
<value letter_id="N">-71</value>
<value letter_id="P">170</value>
<value letter_id="Q">139</value>
<value letter_id="R">-216</value>
<value letter_id="S">75</value>
<value letter_id="T">-20</value>
<value letter_id="V">-96</value>
<value letter_id="W">-597</value>
<value letter_id="Y">-39</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">38</value>
<value letter_id="C">-641</value>
<value letter_id="D">-38</value>
<value letter_id="E">-158</value>
<value letter_id="F">-589</value>
<value letter_id="G">-544</value>
<value letter_id="H">-434</value>
<value letter_id="I">-148</value>
<value letter_id="K">-40</value>
<value letter_id="L">-393</value>
<value letter_id="M">-102</value>
<value letter_id="N">-384</value>
<value letter_id="P">148</value>
<value letter_id="Q">25</value>
<value letter_id="R">-82</value>
<value letter_id="S">129</value>
<value letter_id="T">223</value>
<value letter_id="V">-40</value>
<value letter_id="W">-597</value>
<value letter_id="Y">-508</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-731</value>
<value letter_id="C">-716</value>
<value letter_id="D">-1010</value>
<value letter_id="E">-1021</value>
<value letter_id="F">-720</value>
<value letter_id="G">-1003</value>
<value letter_id="H">-1062</value>
<value letter_id="I">401</value>
<value letter_id="K">-994</value>
<value letter_id="L">-20</value>
<value letter_id="M">-592</value>
<value letter_id="N">-934</value>
<value letter_id="P">-1026</value>
<value letter_id="Q">-1026</value>
<value letter_id="R">-1048</value>
<value letter_id="S">-978</value>
<value letter_id="T">-720</value>
<value letter_id="V">181</value>
<value letter_id="W">-953</value>
<value letter_id="Y">-854</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">3</value>
<value letter_id="C">-641</value>
<value letter_id="D">-148</value>
<value letter_id="E">-7</value>
<value letter_id="F">-273</value>
<value letter_id="G">-134</value>
<value letter_id="H">-34</value>
<value letter_id="I">-109</value>
<value letter_id="K">35</value>
<value letter_id="L">6</value>
<value letter_id="M">-47</value>
<value letter_id="N">-71</value>
<value letter_id="P">196</value>
<value letter_id="Q">101</value>
<value letter_id="R">-61</value>
<value letter_id="S">-3</value>
<value letter_id="T">-75</value>
<value letter_id="V">-151</value>
<value letter_id="W">-597</value>
<value letter_id="Y">74</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1036</value>
<value letter_id="C">-1015</value>
<value letter_id="D">-820</value>
<value letter_id="E">381</value>
<value letter_id="F">-1044</value>
<value letter_id="G">-952</value>
<value letter_id="H">-968</value>
<value letter_id="I">-1068</value>
<value letter_id="K">-1068</value>
<value letter_id="L">-1108</value>
<value letter_id="M">-1085</value>
<value letter_id="N">-954</value>
<value letter_id="P">-1039</value>
<value letter_id="Q">-981</value>
<value letter_id="R">-1040</value>
<value letter_id="S">-1079</value>
<value letter_id="T">-1037</value>
<value letter_id="V">-1093</value>
<value letter_id="W">-972</value>
<value letter_id="Y">-1010</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-161</value>
<value letter_id="C">-641</value>
<value letter_id="D">76</value>
<value letter_id="E">234</value>
<value letter_id="F">-182</value>
<value letter_id="G">-53</value>
<value letter_id="H">130</value>
<value letter_id="I">-52</value>
<value letter_id="K">-24</value>
<value letter_id="L">-129</value>
<value letter_id="M">-7</value>
<value letter_id="N">21</value>
<value letter_id="P">-255</value>
<value letter_id="Q">-35</value>
<value letter_id="R">-287</value>
<value letter_id="S">-31</value>
<value letter_id="T">59</value>
<value letter_id="V">-121</value>
<value letter_id="W">-597</value>
<value letter_id="Y">-224</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-30</value>
<value letter_id="C">-641</value>
<value letter_id="D">121</value>
<value letter_id="E">65</value>
<value letter_id="F">-126</value>
<value letter_id="G">-2</value>
<value letter_id="H">22</value>
<value letter_id="I">-109</value>
<value letter_id="K">-99</value>
<value letter_id="L">-62</value>
<value letter_id="M">-102</value>
<value letter_id="N">21</value>
<value letter_id="P">64</value>
<value letter_id="Q">37</value>
<value letter_id="R">-81</value>
<value letter_id="S">41</value>
<value letter_id="T">-36</value>